social_media:
  facebook_share:
    text: 'Jaa Facebook-palvelussa'
    api_url: 'http://www.facebook.com/share.php?u=[current-page:url]&title=[current-page:title]'
    attributes: "target|_blank\r\nclass|facebook-share"
  linkedin:
    text: 'Jaa LinkedIn-palvelussa'
    api_url: 'https://www.linkedin.com/sharing/share-offsite/?url=[current-page:url]'
    attributes: "target|_blank\r\nclass|linkedin"
  twitter:
    text: 'Jaa X-palvelussa'
    api_url: 'https://twitter.com/intent/tweet?url=[current-page:url]&status=[current-page:title]+[current-page:url]'
    attributes: "target|_blank\r\nclass|twitter"
  email:
    text: 'Lähetä sivu sähköpostitse'
  facebook_msg:
    attributes: "target|_blank\r\nclass|facebook-msg\r\nrel|noopener noreferrer"
  pinterest:
    attributes: "target|_blank\r\nclass|pinterest\r\nrel|noopener noreferrer"
  whatsapp:
    attributes: "class|whatsapp show-for-small-only\r\ndata-action|share/whatsapp/share"
  print:
    text: Print
