_core:
  default_config_hash: NGxFi-xycxrzrGVZtCUl7MACi0jVRk130tNabvIN6ng
content_root: ''
assertiveness: smart
no_load: ''
embedded_content_warning: ''
download_links: ''
ignore_link_strings: ''
link_ignore_selector: 'svg.ext, svg.mailto, .link-purpose-text'
hidden_handlers: ''
disable_live: false
live_h2: 'form[id^="node-"] #edit-body-wrapper .ck-content'
ck5_table_headers: row
ignore_containers: ''
allow_overflow: ''
