always_save_userinfo: true
connect_existing_users: true
override_registration_settings: true
end_session_enabled: true
user_login_display: above
userinfo_mappings:
  timezone: zoneinfo
role_mappings: {  }
