_core:
  default_config_hash: 0cSFmtaooEoYv15Hw6hl0XsvZE6k1DKbqjukwUjZi6Y
client_key: ''
environment: ''
release: ''
log_levels:
  1: 1
  2: 2
  3: 3
  4: 0
  5: 0
  6: 0
  7: 0
  8: 0
stack: true
timeout: !!float 2
message_limit: 2048
trace: false
fatal_error_handler: true
fatal_error_handler_memory: 2560
javascript_error_handler: false
drush_error_handler: false
public_dsn: ''
ssl: verify_ssl
ca_cert: ''
ignored_channels: {  }
send_user_data: false
rate_limit: 0
send_request_body: false
request_tracing: false
traces_sample_rate: null
browser_traces_sample_rate: null
database_tracing: false
twig_tracing: false
auto_session_tracking: false
