on:
  workflow_dispatch:
  repository_dispatch:
    types: [ build_artifact ]
  schedule:
    - cron:  '0 0 * * 0'
name: Build artifacts
jobs:
  build:
    uses: city-of-helsinki/drupal-gh-actions/.github/workflows/build-artifact.yml@UHF-12582
    secrets:
      sentry_crons: ${{ secrets.SENTRY_CRONS }}
