on:
  push:
    branches:
      - dev
name: Robot
env:
  COMPOSE_PROFILES: testing
  COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
  XDEBUG_MODE: off
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Download latest dump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run download -n latest.sql

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Build project
        run: |
          sudo apt-get update
          make setup-robo

      - name: Run tests
        run: make run-robo-tests

      - name: Export app logs
        run: docker compose logs app > logs.txt

      - name: Create an artifact from test report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: results
          path: |
            logs.txt
            helfi-test-automation-python/robotframework-reports/
          retention-days: 2
