on:
  pull_request:
  push:
    branches: ['main', 'dev']
name: CI
jobs:
  tests:
    uses: city-of-helsinki/drupal-gh-actions/.github/workflows/project-tests.yml@UHF-11502
    secrets:
      sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
